name: Deploy Django to Azure

on:
  push:
    branches:
      - prod  # Altere para 'main' se for sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Clonar o repositÃ³rio
        uses: actions/checkout@v3

      - name: ğŸ Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: ğŸ“š Instalar dependÃªncias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ğŸ“ Coletar arquivos estÃ¡ticos
        run: |
          python manage.py collectstatic --noinput

      - name: ğŸ—ƒï¸ Aplicar migraÃ§Ãµes do banco
        run: |
          python manage.py migrate

      - name: ğŸš€ Deploy para Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: PaginaViradaStore
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
